<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Codev.Avalonia\Assets\codev-icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="artifacts\**\*.cs" />
    <Page Remove="artifacts\**\*.xaml" />
    <ApplicationDefinition Remove="artifacts\**\*.xaml" />
    <Compile Remove="Codev.Tests\**\*.cs" />
    <Compile Remove="Codev.Windows.Tests\**\*.cs" />
    <Compile Remove="Codev.Avalonia\**\*.cs" />
    <Compile Remove="Codev.Core\**\*.cs" />
    <Page Remove="Codev.Tests\**\*.xaml" />
    <ApplicationDefinition Remove="Codev.Tests\**\*.xaml" />
    <Page Remove="Codev.Windows.Tests\**\*.xaml" />
    <ApplicationDefinition Remove="Codev.Windows.Tests\**\*.xaml" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="Codev.Core\Codev.Core.csproj" />
    <Resource Include="Codev.Avalonia\Assets\codev-icon.ico" Link="Assets\codev-icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="10.0.10" />
  </ItemGroup>

</Project>
