<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Codev.Tests\**\*.cs" />
    <Page Remove="Codev.Tests\**\*.xaml" />
    <ApplicationDefinition Remove="Codev.Tests\**\*.xaml" />
  </ItemGroup>

</Project>
